default_region      = "us-east-1"
docker_username     = "matlau"
github_username     = "MatthewCYLau"
github_project_name = "quickstart-react-material-ui"
app_name            = "react-material-ui-app"
environment         = "staging"
